import type { DiagnosisSuggestion } from './types';

export const MOCK_DIAGNOSES: DiagnosisSuggestion[] = [
  { id: 1, term: "Fever", namasteCode: "Jwara", icd11Code: "1A00", confidence: 95 },
  { id: 2, term: "High Blood Pressure", namasteCode: "Uchcha Raktachapa", icd11Code: "BA01", confidence: 98 },
  { id: 3, term: "Common Cold", namasteCode: "Pratishyaya", icd11Code: "1E20", confidence: 92 },
  { id: 4, term: "Diabetes Mellitus", namasteCode: "Madhumeha", icd11Code: "5A14", confidence: 99 },
  { id: 5, term: "Headache", namasteCode: "Shirahshoola", icd11Code: "8A80", confidence: 90 },
  { id: 6, term: "Vata Dosha Imbalance", namasteCode: "Vata Dosha", icd11Code: "QC81", confidence: 85, note: "Ayurveda concept mapped to ICD 'Symptoms concerning nervous and musculoskeletal systems'" },
  { id: 7, term: "Pitta Dosha Imbalance", namasteCode: "Pitta Dosha", icd11Code: "ME03", confidence: 84, note: "Ayurveda concept mapped to ICD 'Symptoms concerning the digestive system'" },
  { id: 8, term: "Kapha Dosha Imbalance", namasteCode: "Kapha Dosha", icd11Code: "MD90", confidence: 82, note: "Ayurveda concept mapped to ICD 'Symptoms concerning nutrition or metabolism'" },
  { id: 9, term: "Hypertension", namasteCode: "Uchcha Raktachapa", icd11Code: "BA01", confidence: 97 },
  { id: 10, term: "Hyperthermia", namasteCode: "Jwara", icd11Code: "1A00", confidence: 88 },
  { id: 11, term: "Arthritis", namasteCode: "Sandhivata", icd11Code: "FA20", confidence: 94 },
  { id: 12, term: "Asthma", namasteCode: "Shwasa", icd11Code: "CA23", confidence: 96 },
  { id: 13, term: "Anemia", namasteCode: "Pandu", icd11Code: "3A00", confidence: 93 },
  { id: 14, term: "Jaundice", namasteCode: "Kamala", icd11Code: "DB90", confidence: 91 },
  { id: 15, term: "Migraine", namasteCode: "Ardhavabhedaka", icd11Code: "8A80.0", confidence: 89 },
  { id: 16, term: "Insomnia", namasteCode: "Anidra", icd11Code: "7A20", confidence: 87 },
  { id: 17, term: "Depression", namasteCode: "Avasada", icd11Code: "6A70", confidence: 95 },
  { id: 18, term: "Skin Allergy", namasteCode: "Twak Vikara", icd11Code: "EK90", confidence: 86 },
  { id: 19, term: "Gastritis", namasteCode: "Amlapitta", icd11Code: "DD91", confidence: 90 },
  { id: 20, term: "Indigestion", namasteCode: "Agnimandya", icd11Code: "ME01", confidence: 88 },
  { id: 21, term: "Chronic Cough", namasteCode: "Kasa", icd11Code: "1E61", confidence: 92 },
  { id: 22, term: "Obesity", namasteCode: "Sthaulya", icd11Code: "5B81", confidence: 97 },
  { id: 23, term: "Kidney Stone", namasteCode: "Vrikka Ashmari", icd11Code: "GB30", confidence: 91 },
  { id: 24, term: "Back Pain", namasteCode: "Kati Shula", icd11Code: "ME84.2", confidence: 89 },
  { id: 25, term: "Eczema", namasteCode: "Vicharchika", icd11Code: "EK30", confidence: 85 },
  { id: 26, term: "Psoriasis", namasteCode: "Kitibha", icd11Code: "EA90.0", confidence: 92 },
  { id: 27, term: "Acne", namasteCode: "Yauvan Pidika", icd11Code: "ED80.0", confidence: 94 },
  { id: 28, term: "Vitiligo", namasteCode: "Shvitra", icd11Code: "ED91.0", confidence: 88 },
  { id: 29, term: "Urticaria", namasteCode: "Sheetapitta", icd11Code: "EK70", confidence: 87 },
  { id: 30, term: "Irritable Bowel Syndrome", namasteCode: "Grahani", icd11Code: "DD90.0", confidence: 91 },
  { id: 31, term: "Peptic Ulcer", namasteCode: "Parinama Shula", icd11Code: "DA41", confidence: 93 },
  { id: 32, term: "Hemorrhoids", namasteCode: "Arsha", icd11Code: "DB50", confidence: 95 },
  { id: 33, term: "Gallstones", namasteCode: "Pittashmari", icd11Code: "DC10", confidence: 90 },
  { id: 34, term: "Constipation", namasteCode: "Vibandha", icd11Code: "ME00", confidence: 96 },
  { id: 35, term: "Diarrhea", namasteCode: "Atisara", icd11Code: "1A02", confidence: 94 },
  { id: 36, term: "Heart Failure", namasteCode: "Hridroga", icd11Code: "BA40", confidence: 98 },
  { id: 37, term: "Coronary Artery Disease", namasteCode: "Hrid Dhamani Roga", icd11Code: "BA51", confidence: 97 },
  { id: 38, term: "Arrhythmia", namasteCode: "Hrid Gati Vaishamya", icd11Code: "BA80", confidence: 89 },
  { id: 39, term: "Myocardial Infarction", namasteCode: "Hrid Aghata", icd11Code: "BA41.0", confidence: 99 },
  { id: 40, term: "Hypothyroidism", namasteCode: "Galaganda", icd11Code: "5A00", confidence: 96 },
  { id: 41, term: "Hyperthyroidism", namasteCode: "Ati Galaganda", icd11Code: "5A01", confidence: 95 },
  { id: 42, term: "Polycystic Ovary Syndrome (PCOS)", namasteCode: "Artava Kshaya", icd11Code: "5A91.0", confidence: 93 },
  { id: 43, term: "Epilepsy", namasteCode: "Apasmara", icd11Code: "8A60", confidence: 94 },
  { id: 44, term: "Parkinson's Disease", namasteCode: "Kampa Vata", icd11Code: "8A00.0", confidence: 92 },
  { id: 45, term: "Alzheimer's Disease", namasteCode: "Smriti Nasha", icd11Code: "8A20", confidence: 90 },
  { id: 46, term: "Stroke", namasteCode: "Pakshaghata", icd11Code: "8B21", confidence: 98 },
  { id: 47, term: "Vertigo", namasteCode: "Bhrama", icd11Code: "AB01", confidence: 88 },
  { id: 48, term: "Bronchitis", namasteCode: "Kasa Roga", icd11Code: "CA20", confidence: 91 },
  { id: 49, term: "Pneumonia", namasteCode: "Shvasanaka Jvara", icd11Code: "1E40", confidence: 97 },
  { id: 50, term: "Tuberculosis", namasteCode: "Rajayakshma", icd11Code: "1B10", confidence: 96 },
  { id: 51, term: "Sinusitis", namasteCode: "Pratishyaya", icd11Code: "CA0G", confidence: 93 },
  { id: 52, term: "Osteoarthritis", namasteCode: "Sandhigata Vata", icd11Code: "FA00", confidence: 95 },
  { id: 53, term: "Rheumatoid Arthritis", namasteCode: "Amavata", icd11Code: "FA20.0", confidence: 94 },
  { id: 54, term: "Gout", namasteCode: "Vatarakta", icd11Code: "5C40.0", confidence: 92 },
  { id: 55, term: "Osteoporosis", namasteCode: "Asthi Kshaya", icd11Code: "FB80.2", confidence: 90 },
  { id: 56, term: "Anxiety Disorder", namasteCode: "Chittodvega", icd11Code: "6B00", confidence: 96 },
  { id: 57, term: "Bipolar Disorder", namasteCode: "Manodvaikalyam", icd11Code: "6A60", confidence: 91 },
  { id: 58, term: "Schizophrenia", namasteCode: "Unmada", icd11Code: "6A20", confidence: 89 },
  { id: 59, term: "Obsessive-Compulsive Disorder", namasteCode: "Atatvabhinivesha", icd11Code: "6B20", confidence: 93 },
  { id: 60, term: "Urinary Tract Infection (UTI)", namasteCode: "Mutrakrichra", icd11Code: "GB00", confidence: 95 },
  { id: 61, term: "Benign Prostatic Hyperplasia (BPH)", namasteCode: "Vatastheela", icd11Code: "GC50", confidence: 90 },
  { id: 62, term: "Malaria", namasteCode: "Vishama Jwara", icd11Code: "1F40", confidence: 97 },
  { id: 63, term: "Dengue Fever", namasteCode: "Danda Jwara", icd11Code: "1F20", confidence: 96 },
  { id: 64, term: "Chickenpox", namasteCode: "Masurika", icd11Code: "1E90", confidence: 98 },
  { id: 65, term: "Typhoid Fever", namasteCode: "Sannipata Jwara", icd11Code: "1A40", confidence: 94 },
  { id: 66, term: "Cataract", namasteCode: "Timira", icd11Code: "9B10", confidence: 95 },
  { id: 67, term: "Glaucoma", namasteCode: "Adhimantha", icd11Code: "9C00", confidence: 92 },
  { id: 68, term: "Conjunctivitis", namasteCode: "Abhishyanda", icd11Code: "9A00", confidence: 93 },
  { id: 69, term: "Tonsillitis", namasteCode: "Tundikeri", icd11Code: "CA0A.0", confidence: 89 },
  { id: 70, term: "Otitis Media", namasteCode: "Karna Shula", icd11Code: "AB20", confidence: 88 },
  { id: 71, term: "Varicose Veins", namasteCode: "Sira Granthi", icd11Code: "BB70", confidence: 90 },
  { id: 72, term: "Fatty Liver Disease", namasteCode: "Yakrit Roga", icd11Code: "DC70", confidence: 94 },
  { id: 73, term: "Allergic Rhinitis", namasteCode: "Vataja Pratishyaya", icd11Code: "CA0J", confidence: 91 },
  { id: 74, term: "Fibromyalgia", namasteCode: "Mamsa Dhatu Gata Vata", icd11Code: "ME80", confidence: 87 },
  { id: 75, term: "Chronic Kidney Disease", namasteCode: "Vrikka Roga", icd11Code: "GB61", confidence: 96 },
  { id: 76, term: "Carpal Tunnel Syndrome", namasteCode: "Manibandha Sandhigata Vata", icd11Code: "8C10.0", confidence: 89 },
  { id: 77, term: "Menstrual Cramps", namasteCode: "Artava Shula", icd11Code: "GA34.0", confidence: 95 },
  { id: 78, term: "Endometriosis", namasteCode: "Yonivyapad", icd11Code: "GA10.0", confidence: 91 },
  { id: 79, term: "Celiac Disease", namasteCode: "Annadravashula", icd11Code: "DA70.0", confidence: 90 },
  { id: 80, term: "Sepsis", namasteCode: "Rakta Dhatu Gata Jwara", icd11Code: "1G40", confidence: 98 },
  { id: 81, term: "Food Poisoning", namasteCode: "Visa Suchika", icd11Code: "1A07", confidence: 93 },
  { id: 82, term: "Motion Sickness", namasteCode: "Gati Vibhrama", icd11Code: "AB02.1", confidence: 86 },
  { id: 83, term: "Sunburn", namasteCode: "Surya Dagdha", icd11Code: "EH50.0", confidence: 90 },
];
